# Generated by Django 3.0.6 on 2020-06-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data_pub',
            new_name='date_pub',
        ),
    ]
